name: scilus_website build

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  deploy:
    runs-on: scil-website-runners
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependancies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          git

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          # extended: true

      - name: Build
        run: hugo -D -F -b "https://scil.usherbrooke.ca" -d scil.usherbrooke.ca
      - name: Deploy
        run: rsync --delete -r "$WORKSPACE/scil.usherbrooke.ca/" bora2502@scil.usherbrooke.ca:/var/www/bk_scil.usherbrooke.ca/