name: scilus_website build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: scil-website-runners

    steps:
      - name: Install dependancies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          git rsync

      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: ''
      
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          wait-timeout-minutes: 5
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: arnaudbore

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.123.8'
          extended: true

      - name: Build
        run: hugo -D -F -b "https://scil.usherbrooke.ca" -d scil.usherbrooke.ca
      - name: Deploy
        run: rsync -v --delete -r "$WORKSPACE/scil.usherbrooke.ca/" bora2502@scil.usherbrooke.ca:/var/www/bk_scil.usherbrooke.ca/