name: scilus_website build

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: scil-website-runners

    steps:
      - name: Install dependancies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          git

      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: ''

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          extended: true

      - name: Build
        run: hugo -D -F -b "https://scil.usherbrooke.ca" -d scil.usherbrooke.ca
      - name: Deploy
        run: rsync --delete -r "$WORKSPACE/scil.usherbrooke.ca/" bora2502@scil.usherbrooke.ca:/var/www/bk_scil.usherbrooke.ca/